spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:test # In-Memory mode
    driver-class-name: org.h2.Driver
    username: sa
    password:

